# Generated by Django 3.2.9 on 2022-01-17 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='reader',
        ),
        migrations.AddField(
            model_name='followers',
            name='reader',
            field=models.ManyToManyField(related_name='Followers_reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
