# Generated by Django 3.2.9 on 2022-01-18 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220117_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='reader',
            field=models.ManyToManyField(null=True, related_name='Followers_reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
