# Generated by Django 3.2.9 on 2022-01-18 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_followers_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='reader',
            field=models.ManyToManyField(related_name='Followers_reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
